### PR TITLE
Initial implementation of the SortFilterProxyModel QML plugin

### LINKED ISSUE #4: Use appropriate Q_DECL_IMPORT/Q_DECL_EXPORT macros for exported symbols
I haven't tested a Windows build of this code yet, but I would expect it to fail. The problem is, Windows DLLs really need the `dllimport` and `dllexport` stuff when building. If they're not used appropriately, the builds will fail.

Have a look at the other code within our libraries - this is the reason for the "export" headers in each repository, which are responsible for using the correct macro based on whether or not it's a library build or the library is being used/linked externally.

See this page for more information: https://doc.qt.io/qt-5/sharedlibrary.html

### PR DESCRIPTION
**Pull request by saidinesh5**
Also Fixes #4

### CODE REVIEW

File: qqmlsortfilterproxymodel_plugin.cpp [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+#include <qqml.h>
+
+#include "qqmlsortfilterproxymodel.h"
+#include "filter.h"
+#include "sorter.h"
+
+using namespace qqsfpm;
+
+void QQmlsortfilterproxymodelPlugin::registerTypes(const char *uri)
```
Comment (crozeg) [inline qqmlsortfilterproxymodel_plugin.cpp]: unused parameter `uri`.

File: sortfilterproxymodel.qbs [hunk 2]
```diff
@@ -59,6 +61,7 @@ Product
         [
             "filter.cpp",
             "qqmlsortfilterproxymodel.cpp",
+            "qqmlsortfilterproxymodel_plugin.cpp",
```
Comment (crozeg) [inline sortfilterproxymodel.qbs:65]: please rename this file to `qqmlsortfilterproxymodelplugin.cpp`.

File: sortfilterproxymodel.qbs [hunk 3]
```diff
@@ -70,7 +73,47 @@ Product
         [
             "filter.h",
             "qqmlsortfilterproxymodel.h",
+            "qqmlsortfilterproxymodelexport.h",
+            "qqmlsortfilterproxymodel_plugin.h",
```
Comment (crozeg) [inline sortfilterproxymodel.qbs:78]: please rename this file to `qqmlsortfilterproxymodelplugin.h`.

File: sortfilterproxymodel.qbs [hunk 4]
```diff
@@ -70,7 +73,47 @@ Product
...
+
+            cmd.description = "Copying " + input.fileName + " to " + output.filePath
+            cmd.highlight = "codegen"
+            cmd.sourceCode = function()
+            {
+                File.copy(input.filePath,
+                          output.filePath)
+            }
+
+            return cmd;
```
Comment (crozeg) [inline sortfilterproxymodel.qbs]: remove the `;`.

File: sortfilterproxymodel.qbs [hunk 5]
```diff
@@ -70,7 +73,47 @@ Product
...
+        [
+            "qmldir"
+        ]
+        fileTags: "qbs resources"
+    }
+
+    //FIXME: Replace this to actually install files in the right location
+    Rule
+    {
+        inputs: ["qbs resources"]
```
Comment (crozeg) [inline sortfilterproxymodel.qbs]:
```
inputs: 
[
    "qbs resources"
]
```

File: sortfilterproxymodel.qbs [hunk 6]
```diff
@@ -70,7 +73,47 @@ Product
...
+
+        Artifact
+        {
+            filePath: FileInfo.joinPaths(product.destinationDirectory,
+                                         "qmldir")
+            fileTags: ["copied qbs resources"]
```
Comment (crozeg) [inline sortfilterproxymodel.qbs]:
```
fileTags: 
[
    "copied qbs resources"
]
```

File: sortfilterproxymodel.qbs [hunk 7]
```diff
@@ -70,7 +73,47 @@ Product
...
+    {
+        name: "Other files"
+        files:
+        [
+            "qmldir"
+        ]
+        fileTags: "qbs resources"
+    }
+
+    //FIXME: Replace this to actually install files in the right location
```
Comment (crozeg) [inline sortfilterproxymodel.qbs:93]: is this open?

**Review by crozeg — CHANGES_REQUESTED** [review]
In linux I can build and run this plugin, when I add the cpp.cxxLanguageVersion: "c++11" to the qbs-file.
Now I test it in Windows.

File: sortfilterproxymodel.qbs [hunk 8]
```diff
@@ -1,12 +1,14 @@
 import qbs 1.0
+import qbs.File
+import qbs.FileInfo
 
 Product
 {
-    name: "sortfilterproxymodel"
-    type: "dynamiclibrary"
+    name: "SortFilterProxyModel"
+    type: ["dynamiclibrary", "copied qbs resources"]
```
Comment (johnbivens) [inline sortfilterproxymodel.qbs:8]: Oh, interesting. I didn't realize `copied qbs resources` was a type. Is this some sort of hack, or one of those hidden/undocumented things? Hopefully this doesn't change in future Qbs versions.

File: qqmlsortfilterproxymodel_plugin.h [hunk 9]
```diff
@@ -0,0 +1,12 @@
+#pragma once
+
+#include <QQmlExtensionPlugin>
+
+class QQmlsortfilterproxymodelPlugin : public QQmlExtensionPlugin
```
Comment (johnbivens) [inline qqmlsortfilterproxymodel_plugin.h]: I assume we'll also need `QQMLSORTFILTERPROXYMODEL_EXPORT` here, but @crozeg's Windows tests should be able to confirm it.

File: qqmlsortfilterproxymodel_plugin.cpp [hunk 10]
```diff
@@ -0,0 +1,31 @@
...
+{   
+    //Filter
+    qmlRegisterUncreatableType<Filter>("SortFilterProxyModel", 0, 2, "Filter", "Filter is an abstract class");
```
Comment (johnbivens) [inline qqmlsortfilterproxymodel_plugin.cpp]: None of these fit our code guidelines for line breaks between parameters (*don't kill me*). However, I would actually prefer keeping these as-is *if they are consistent with the style used in the rest of this 3rd-party code*. So I guess my comment would be: please make sure the code style used in this file is consistent with the rest of the code style in this repository (if it isn't already).

File: filter.cpp [hunk 11]
```diff
@@ -444,6 +444,6 @@ void registerFilterTypes() {
     qmlRegisterType<AllOfFilter>("SortFilterProxyModel", 0, 2, "AllOf");
 }
 
-Q_COREAPP_STARTUP_FUNCTION(registerFilterTypes)
+//Q_COREAPP_STARTUP_FUNCTION(registerFilterTypes)
```
Comment (johnbivens) [inline filter.cpp]: If this isn't needed, please just go ahead and delete it.

File: qqmlsortfilterproxymodel.cpp [hunk 12]
```diff
@@ -370,6 +370,6 @@ void registerQQmlSortFilterProxyModelTypes() {
     qmlRegisterType<QQmlSortFilterProxyModel>("SortFilterProxyModel", 0, 2, "SortFilterProxyModel");
 }
 
-Q_COREAPP_STARTUP_FUNCTION(registerQQmlSortFilterProxyModelTypes)
+//Q_COREAPP_STARTUP_FUNCTION(registerQQmlSortFilterProxyModelTypes)
```
Comment (johnbivens) [inline qqmlsortfilterproxymodel.cpp]: Ditto (delete if unnecessary).

File: sorter.cpp [hunk 13]
```diff
@@ -215,6 +215,6 @@ void registerSorterTypes() {
     qmlRegisterType<ExpressionSorter>("SortFilterProxyModel", 0, 2, "ExpressionSorter");
 }
 
-Q_COREAPP_STARTUP_FUNCTION(registerSorterTypes)
+//Q_COREAPP_STARTUP_FUNCTION(registerSorterTypes)
```
Comment (johnbivens) [inline sorter.cpp]: This should also be deleted if it isn't necessary.

File: qqmlsortfilterproxymodelexport.h [hunk 14]
```diff
@@ -0,0 +1,12 @@
...
+
+#include <QtCore/qglobal.h>
+
+#if defined(SORT_FILTER_PROXY_MODEL_LIBRARY_BUILD)
+#  define QQMLSORTFILTERPROXYMODEL_EXPORT Q_DECL_EXPORT
+#else
+#  define QQMLSORTFILTERPROXYMODEL_EXPORT Q_DECL_IMPORT
+#endif
+
+#endif // QRM_OBJECT_DICTIONARY_MODEL_EXPORT_H
```
Comment (johnbivens) [inline qqmlsortfilterproxymodelexport.h]: Please change this here (`QQMLSORTFILTERPROXYMODEL_EXPORT_H`).

**Review by johnbivens — CHANGES_REQUESTED** [review]

File: sortfilterproxymodel.qbs (hunk 2 above)
Comment (saidinesh5) [reply sortfilterproxymodel.qbs:65]: Ah should we? that file was automatically created by QtCreator when I selected the type QML Plugin.

File: sortfilterproxymodel.qbs (hunk 8 above)
Comment (saidinesh5) [reply sortfilterproxymodel.qbs:8]: @johnbivens So the way qbs works is via. fileTags. "copied qbs resources" is the fileTags for the artifacts described here: 
https://github.com/Proemion/SortFilterProxyModel/blob/72678663b1988cf3a2a5885f8fabb5e521e93fab/sortfilterproxymodel.qbs#L101

Also, the place i got stuck, trying to figure out why this rule wasn't getting executed was:
I was using input: ["qmldir"] instead of:      https://github.com/Proemion/SortFilterProxyModel/blob/72678663b1988cf3a2a5885f8fabb5e521e93fab/sortfilterproxymodel.qbs#L95 , and tagging the group of qbs resources with: 
https://github.com/Proemion/SortFilterProxyModel/blob/72678663b1988cf3a2a5885f8fabb5e521e93fab/sortfilterproxymodel.qbs#L89

File: qqmlsortfilterproxymodel_plugin.h (hunk 9 above)
Comment (saidinesh5) [reply qqmlsortfilterproxymodel_plugin.h]: I think this should work though. Not sure but this file was autogenerated by QtCreator when I selected New Project >  Library > Qt Quick 2 Extension Plugin.

File: qqmlsortfilterproxymodel_plugin.cpp (hunk 10 above)
Comment (saidinesh5) [reply qqmlsortfilterproxymodel_plugin.cpp]: This was actually copy pasted code from: https://github.com/Proemion/SortFilterProxyModel/blob/72678663b1988cf3a2a5885f8fabb5e521e93fab/filter.cpp#L436

https://github.com/Proemion/SortFilterProxyModel/blob/72678663b1988cf3a2a5885f8fabb5e521e93fab/qqmlsortfilterproxymodel.cpp#L369

https://github.com/Proemion/SortFilterProxyModel/blob/72678663b1988cf3a2a5885f8fabb5e521e93fab/sorter.cpp#L212

So, didn't change these things.

(The commented out  //Q_COREAPP_STARTUP_FUNCTION(registerFilterTypes) , is to prevent it from registering the library twice, so the registerXTypes function from the .cpp files are never called)

File: sortfilterproxymodel.qbs (hunk 8 above)
Comment (saidinesh5) [reply sortfilterproxymodel.qbs:8]: @johnbivens btw this really is a hack put in place for now, as we are using

destinationDirectory: project.deployDirectory + "/" + name

instead of actual install / deploy features provided by QBS. This should be cleaned up along with the rest once we start that cleanup.

File: sortfilterproxymodel.qbs (hunk 7 above)
Comment (saidinesh5) [reply sortfilterproxymodel.qbs:93]: We have to create an issue/fix this in quarks/avalon/etc.. to actually "install" files, instead of using the 
destinationDirectory: project.deployDirectory . So this is to be cleaned up then.

File: sortfilterproxymodel.qbs (hunk 2 above)
Comment (johnbivens) [reply sortfilterproxymodel.qbs:65]: I'm fine with this staying like this if you'd prefer, as this is a third-party library.

File: sortfilterproxymodel.qbs (hunk 7 above)
Comment (johnbivens) [reply sortfilterproxymodel.qbs:93]: @saidinesh5 Ok, please open an issue for this in the Quarks superrepo.

File: sortfilterproxymodel.qbs (hunk 8 above)
Comment (johnbivens) [reply sortfilterproxymodel.qbs:8]: Cool, thanks for the explanation :smile:

File: qqmlsortfilterproxymodel_plugin.h (hunk 9 above)
Comment (johnbivens) [reply qqmlsortfilterproxymodel_plugin.h]: @saidinesh5 Hmm... we'll see what the tests say. I've had enough problems with the stupid DLL import/export nonsense, so I'm afraid this may be no different. But we'll see.

While I'm at it, I just noticed the name of this class. I know it was generated, but could you please change this to `QQmlSortFilterProxyModelPlugin`?

File: sortfilterproxymodel.qbs [hunk 15]
```diff
@@ -49,6 +49,7 @@ Product
         }
 
         cpp.includePaths: [ "." ]
+        cpp.cxxLanguageVersion: "c++11"
```
Comment (crozeg) [inline sortfilterproxymodel.qbs]: Please move this to line 36, after the another `cpp.includePaths: [ "." ]`.

**Review by crozeg — APPROVED** [review]

**Comment by crozeg** [comment]
Windows tests was successfully.

**Review by johnbivens — APPROVED** [review]
